const Conversations = {
  GET_ALL_CONVERSATIONS_OF_CURRENT_USER: '  GET_ALL_CONVERSATIONS_OF_CURRENT_USER',
  CREATE_NEW_CONVERSATION: 'CREATE_NEW_CONVERSATION',
  SET_SELECTED_CATEGORY: 'SET_SELECTED_CATEGORY'
};
export default Conversations;
